// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqofjufogucbdvccgtva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxb2ZqdWZvZ3VjYmR2Y2NndHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDM2ODEsImV4cCI6MjA3NDExOTY4MX0.YKcM9GC6qboP3gDdJpbs7qMS8HiWNUl3LWK7jUzpZ44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});